# Generated by Django 4.0.6 on 2022-08-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='admin',
        ),
    ]
