# Generated by Django 4.0.6 on 2022-08-22 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happ', '0003_delete_payment_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoncard', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('grandtotal', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happ.cart_tb')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happ.user_tb')),
            ],
        ),
    ]
